### ISSUE TITLE
Who is going to commit the report work next ?

### ISSUE THREAD

**Issue by nsatvik** [nsatvik/ts-datamining#1]
I was doing seminar work today! My code changes will come tomo! :dango:

**Comment by samiriff** [comment]
:v: Even I was doing seminar work today....I still haven't completed my seminar work. Did you guys complete the seminar work?

**Comment by vaishakhbn** [comment]
I will start my seminar work in the near future. And yeah the report will be committed in the near future..

**Comment by nsatvik** [comment]
:smoking: :facepunch:

**Comment by vaishakhbn** [comment]
Report Committed..
