### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by vaishakhbn** [nsatvik/ts-datamining#2]
The numbering in the index is completely in roman. We are Indian man, make it into numbers. Also, the headings that I gave are all in capitals and you gave everything small. Choose one thing common. And, implementation chapter appears twice in the whole report. 
And if you finally read this whole thing, say hello to me on whatsapp because I do not expect anybody to read this. 

With Love and Affection,
Badri's Student.

**Comment by nsatvik** [comment]
Aye Aye! Captain... I don't no from where to start! :dash:

**Comment by nsatvik** [comment]
Matter Closed! Sync madi Boss! :+1:  :wink: Cheers!:beers:
