### ISSUE TITLE
Party Over

### ISSUE THREAD

**Issue by nsatvik** [nsatvik/ts-datamining#5]
Report Updated and everything done! Feel free to do anything and everything.
And now it's upto our Abed to get the cream binding and water marking done. :stuck_out_tongue:
@vaishakhbn  :stuck_out_tongue_winking_eye: And we need treat for :princess:

**Comment by vaishakhbn** [comment]
Abed will get it done once the report has been accepted :page_facing_up:  
And treat for what?  :smirk:
